meta:
  description: farmr
  vendor: farmr
  maintainer: farmr
files:
  "/usr/bin/farmr":
    file: farmr_package
    mode: "0755"
    user: "root"
  "/etc/systemd/user/farmr.service":
    file: .github/workflows/farmr.service
    mode: "0644"
    user: "root"
  "/etc/systemd/user/farmr-hpool.service":
    file: .github/workflows/farmr-hpool.service
    mode: "0644"
    user: "root"
  "/etc/farmr/config/config-xch.json":
    file: config/config-xch.json
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xch.json":
    file: blockchain/xch.json
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xfx.json.template":
    file: blockchain/xfx.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/cgn.json.template":
    file: blockchain/cgn.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xgj.json.template":
    file: blockchain/xgj.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/spare.json.template":
    file: blockchain/spare.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xse.json.template":
    file: blockchain/xse.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xfl.json.template":
    file: blockchain/xfl.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/hdd.json.template":
    file: blockchain/hdd.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/avo.json.template":
    file: blockchain/avo.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/gdog.json.template":
    file: blockchain/gdog.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/apple.json.template":
    file: blockchain/apple.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/tad.json.template":
    file: blockchain/tad.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xdg.json.template":
    file: blockchain/xdg.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xka.json.template":
    file: blockchain/xka.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xmz.json.template":
    file: blockchain/xmz.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xtx.json.template":
    file: blockchain/xtx.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/tsit.json.template":
    file: blockchain/tsit.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/cac.json.template":
    file: blockchain/cac.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xcd.json.template":
    file: blockchain/xcd.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/cov.json.template":
    file: blockchain/cov.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/cans.json.template":
    file: blockchain/cans.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xbtc.json.template":
    file: blockchain/xbtc.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/sock.json.template":
    file: blockchain/sock.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xcc.json.template":
    file: blockchain/xcc.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xol.json.template":
    file: blockchain/xol.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/scm.json.template":
    file: blockchain/scm.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/vag.json.template":
    file: blockchain/vag.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/wheat.json.template":
    file: blockchain/wheat.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xfk.json.template":
    file: blockchain/xfk.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/llc.json.template":
    file: blockchain/llc.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xeq.json.template":
    file: blockchain/xeq.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xmx.json.template":
    file: blockchain/xmx.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/six.json.template":
    file: blockchain/six.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/nch.json.template":
    file: blockchain/nch.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/stai.json.template":
    file: blockchain/stai.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/sit.json.template":
    file: blockchain/sit.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xvm.json.template":
    file: blockchain/xvm.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/trz.json.template":
    file: blockchain/trz.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/stor.json.template":
    file: blockchain/stor.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/aec.json.template":
    file: blockchain/aec.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/rolls.json.template":
    file: blockchain/rolls.json.template
    mode: "0644"
    user: "root"
    keep: true
  "/etc/farmr/blockchain/xshib.json.template":
    file: blockchain/xshib.json.template
    mode: "0644"
    user: "root"
    keep: true
units:
  #- .github/workflows/farmr.service
scripts:
  "post-install": .github/workflows/post-inst
user: foo
