#!/bin/bash
echo "[Unit]
Description=farmr

[Service]
Type=forking
RemainAfterExit=yes
WorkingDirectory=/etc/farmr/
#Environment=PATH=/chia/Swar-Chia-Plot-Manager/venv/bin:${PATH}
ExecStart=/usr/bin/tmux new-session -s farmr -d /usr/bin/farmr
ExecStop=/usr/bin/tmux kill-session -t farmr

[Install]
WantedBy=default.target" > /home/*/.config/systemd/user/farmr.service;
systemctl daemon-reload;
